document.addEventListener('DOMContentLoaded', function() {
    // Elementos del DOM
    const elementoTexto = document.getElementById('texto-cita');
    const elementoTitulo = document.getElementById('titulo-cita');
   
    // 1. VERIFICACIÓN DE CARGA ESTÁTICA
    // Si el servidor (GitHub Actions) ya actualizó el HTML, el texto no dirá "Cargando...".
    // En ese caso, no hacemos nada para ahorrar recursos y evitar parpadeos.
    if (elementoTexto && !elementoTexto.textContent.includes("Cargando")) {
        console.log("Devocional cargado estáticamente.");
        return;
    }

    console.log("Cargando devocional dinámicamente (Modo Cliente)...");

    // --- BASE DE DATOS LOCAL DE CITAS (Sin API) ---
    const citasBiblicas = [
        { ref: "Levítico 6:12-13", texto: "12 Y el fuego encendido sobre el altar no se apagará, sino que el sacerdote pondrá en él leña cada mañana, y acomodará el holocausto sobre él, y quemará sobre él la grosura de las ofrendas de paz. 13 El fuego arderá continuamente en el altar; no se apagará." },
        { ref: "Éxodo 13:21-22", texto: "21 Y Jehová iba delante de ellos de día en una columna de nube para guiarlos por el camino, y de noche en una columna de fuego para alumbrarles, a fin de que anduviesen de día y de noche. 22 Nunca se apartó de delante del pueblo la columna de nube de día, ni de noche la columna de fuego." },
        { ref: "Éxodo 27:20-21", texto: "20 Y tú mandarás a los hijos de Israel que te traigan aceite puro de olivas machacadas, para el alumbrado, para hacer arder continuamente las lámparas. 21 En el tabernáculo de reunión, afuera del velo que está delante del testimonio, las pondrán en orden Aarón y sus hijos para que ardan delante de Jehová desde la tarde hasta la mañana, como estatuto perpetuo de los hijos de Israel por sus generaciones." },
        { ref: "Salmos 119:105,130", texto: "105 Lámpara es a mis pies tu palabra, Y lumbrera a mi camino. 130 La exposición de tus palabras alumbra; Hace entender a los simples." },
        { ref: "Proverbios 6:20-23", texto: "20 Guarda, hijo mío, el mandamiento de tu padre, Y no dejes la enseñanza de tu madre; 21 Átalos siempre en tu corazón, Enlázalos a tu cuello. 22 Te guiarán cuando andes; cuando duermas te guardarán; Hablarán contigo cuando despiertes. 23 Porque el mandamiento es lámpara, y la enseñanza es luz, Y camino de vida las reprensiones que te instruyen," },
        { ref: "Génesis 1:2-4", texto: "2 Y la tierra estaba desordenada y vacía, y las tinieblas estaban sobre la faz del abismo, y el Espíritu de Dios se movía sobre la faz de las aguas. 3 Y dijo Dios: Sea la luz; y fue la luz. 4 Y vio Dios que la luz era buena; y separó Dios la luz de las tinieblas." },
        { ref: "1 Timoteo 4:12-16", texto: "12 Ninguno tenga en poco tu juventud, sino sé ejemplo de los creyentes en palabra, conducta, amor, espíritu, fe y pureza. 13 Entre tanto que voy, ocúpate en la lectura, la exhortación y la enseñanza. 14 No descuides el don que hay en ti, que te fue dado mediante profecía con la imposición de las manos del presbiterio. 15 Ocúpate en estas cosas; permanece en ellas, para que tu aprovechamiento sea manifiesto a todos. 16 Ten cuidado de ti mismo y de la doctrina; persiste en ello, pues haciendo esto, te salvarás a ti mismo y a los que te oyeren." },
        { ref: "2 Timoteo 1:6-7", texto: "6 Por lo cual te aconsejo que avives el fuego del don de Dios que está en ti por la imposición de mis manos. 7 Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio." },
        { ref: "2 Timoteo 1:13-14", texto: "13 Retén la forma de las sanas palabras que de mí oíste, en la fe y amor que es en Cristo Jesús. 14 Guarda el buen depósito por el Espíritu Santo que mora en nosotros." },
        { ref: "2 Timoteo 1:13-14", texto: "13 Retén la forma de las sanas palabras que de mí oíste, en la fe y amor que es en Cristo Jesús. 14 Guarda el buen depósito por el Espíritu Santo que mora en nosotros." },
        { ref: "Isaías 6:5-7", texto: "5 Entonces dije: ¡Ay de mí! que soy muerto; porque siendo hombre inmundo de labios, y habitando en medio de pueblo que tiene labios inmundos, han visto mis ojos al Rey, Jehová de los ejércitos. 6 Y voló hacia mí uno de los serafines, teniendo en su mano un carbón encendido, tomado del altar con unas tenazas; 7 y tocando con él sobre mi boca, dijo: He aquí que esto tocó tus labios, y es quitada tu culpa, y limpio tu pecado." },
        { ref: "Isaías 60:1-2", texto: "1 Levántate, resplandece; porque ha venido tu luz, y la gloria de Jehová ha nacido sobre ti. 2 Porque he aquí que tinieblas cubrirán la tierra, y oscuridad las naciones; mas sobre ti amanecerá Jehová, y sobre ti será vista su gloria." },
        { ref: "1 Pedro 1:7-9", texto: "7 para que sometida a prueba vuestra fe, mucho más preciosa que el oro, el cual aunque perecedero se prueba con fuego, sea hallada en alabanza, gloria y honra cuando sea manifestado Jesucristo, 8 a quien amáis sin haberle visto, en quien creyendo, aunque ahora no lo veáis, os alegráis con gozo inefable y glorioso; 9 obteniendo el fin de vuestra fe, que es la salvación de vuestras almas." },
        { ref: "1 Pedro 4:12-13", texto: "12 Amados, no os sorprendáis del fuego de prueba que os ha sobrevenido, como si alguna cosa extraña os aconteciese, 13 sino gozaos por cuanto sois participantes de los padecimientos de Cristo, para que también en la revelación de su gloria os gocéis con gran alegría." },
        { ref: "Lucas 12:35-37", texto: "35 Estén ceñidos vuestros lomos, y vuestras lámparas encendidas; 36 y vosotros sed semejantes a hombres que aguardan a que su señor regrese de las bodas, para que cuando llegue y llame, le abran en seguida. 37 Bienaventurados aquellos siervos a los cuales su señor, cuando venga, halle velando; de cierto os digo que se ceñirá, y hará que se sienten a la mesa, y vendrá a servirles." },
        { ref: "Malaquías 3:2-4", texto: "2 ¿Y quién podrá soportar el tiempo de su venida? ¿o quién podrá estar en pie cuando él se manifieste? Porque él es como fuego purificador, y como jabón de lavadores. 3 Y se sentará para afinar y limpiar la plata; porque limpiará a los hijos de Leví, los afinará como a oro y como a plata, y traerán a Jehová ofrenda en justicia. 4 Y será grata a Jehová la ofrenda de Judá y de Jerusalén, como en los días pasados, y como en los años antiguos." },
        { ref: "Efesios 5:8-12", texto: "8 Porque en otro tiempo erais tinieblas, mas ahora sois luz en el Señor; andad como hijos de luz 9 (porque el fruto del Espíritu es en toda bondad, justicia y verdad), 10 comprobando lo que es agradable al Señor. 11 Y no participéis en las obras infructuosas de las tinieblas, sino más bien reprendedlas; 12 porque vergonzoso es aun hablar de lo que ellos hacen en secreto." },
        { ref: "Efesios 5:8,13-17", texto: "8 Porque en otro tiempo erais tinieblas, mas ahora sois luz en el Señor; andad como hijos de luz 13 Mas todas las cosas, cuando son puestas en evidencia por la luz, son hechas manifiestas; porque la luz es lo que manifiesta todo. 14 Por lo cual dice: Despiértate, tú que duermes, Y levántate de los muertos, Y te alumbrará Cristo. 15 Mirad, pues, con diligencia cómo andéis, no como necios sino como sabios, 16 aprovechando bien el tiempo, porque los días son malos. 17 Por tanto, no seáis insensatos, sino entendidos de cuál sea la voluntad del Señor." },
        { ref: "Filipenses 2:13-15", texto: "13 porque Dios es el que en vosotros produce así el querer como el hacer, por su buena voluntad. 14 Haced todo sin murmuraciones y contiendas, 15 para que seáis irreprensibles y sencillos, hijos de Dios sin mancha en medio de una generación maligna y perversa, en medio de la cual resplandecéis como luminares en el mundo;" },
        { ref: "Hebreos 12:28-29", texto: "28 Así que, recibiendo nosotros un reino inconmovible, tengamos gratitud, y mediante ella sirvamos a Dios agradándole con temor y reverencia; 29 porque nuestro Dios es fuego consumidor." },
        { ref: "1 Corintios 3:11-14", texto: "11 Porque nadie puede poner otro fundamento que el que está puesto, el cual es Jesucristo. 12 Y si sobre este fundamento alguno edificare oro, plata, piedras preciosas, madera, heno, hojarasca, 13 la obra de cada uno se hará manifiesta; porque el día la declarará, pues por el fuego será revelada; y la obra de cada uno cuál sea, el fuego la probará. 14 Si permaneciere la obra de alguno que sobreedificó, recibirá recompensa." },
        { ref: "2 Corintios 4:5-7", texto: "5 Porque no nos predicamos a nosotros mismos, sino a Jesucristo como Señor, y a nosotros como vuestros siervos por amor de Jesús. 6 Porque Dios, que mandó que de las tinieblas resplandeciese la luz, es el que resplandeció en nuestros corazones, para iluminación del conocimiento de la gloria de Dios en la faz de Jesucristo. 7 Pero tenemos este tesoro en vasos de barro, para que la excelencia del poder sea de Dios, y no de nosotros," },
        { ref: "Hechos 2:1-4", texto: "1 Cuando llegó el día de Pentecostés, estaban todos unánimes juntos. 2 Y de repente vino del cielo un estruendo como de un viento recio que soplaba, el cual llenó toda la casa donde estaban sentados; 3 y se les aparecieron lenguas repartidas, como de fuego, asentándose sobre cada uno de ellos. 4 Y fueron todos llenos del Espíritu Santo, y comenzaron a hablar en otras lenguas, según el Espíritu les daba que hablasen." },
        { ref: "Zacarías 13:9", texto: "9 Y meteré en el fuego a la tercera parte, y los fundiré como se funde la plata, y los probaré como se prueba el oro. El invocará mi nombre, y yo le oiré, y diré: Pueblo mío; y él dirá: Jehová es mi Dios." },
        { ref: "Apocalipsis 2:2-5", texto: "2 Yo conozco tus obras, y tu arduo trabajo y paciencia; y que no puedes soportar a los malos, y has probado a los que se dicen ser apóstoles, y no lo son, y los has hallado mentirosos; 3 y has sufrido, y has tenido paciencia, y has trabajado arduamente por amor de mi nombre, y no has desmayado. 4 Pero tengo contra ti, que has dejado tu primer amor. 5 Recuerda, por tanto, de dónde has caído, y arrepiéntete, y haz las primeras obras; pues si no, vendré pronto a ti, y quitaré tu candelero de su lugar, si no te hubieres arrepentido." },
        { ref: "Juan 11:1-5", texto: "1 Estaba entonces enfermo uno llamado Lázaro, de Betania, la aldea de María y de Marta su hermana. 2 (María, cuyo hermano Lázaro estaba enfermo, fue la que ungió al Señor con perfume, y le enjugó los pies con sus cabellos.) 3 Enviaron, pues, las hermanas para decir a Jesús: Señor, he aquí el que amas está enfermo. 4 Oyéndolo Jesús, dijo: Esta enfermedad no es para muerte, sino para la gloria de Dios, para que el Hijo de Dios sea glorificado por ella. 5 Y amaba Jesús a Marta, a su hermana y a Lázaro." },
        { ref: "Juan 3:19-21", texto: "19 Y esta es la condenación: que la luz vino al mundo, y los hombres amaron más las tinieblas que la luz, porque sus obras eran malas. 20 Porque todo aquel que hace lo malo, aborrece la luz y no viene a la luz, para que sus obras no sean reprendidas. 21 Mas el que practica la verdad viene a la luz, para que sea manifiesto que sus obras son hechas en Dios." },
        { ref: "Malaquías 3:11-12", texto: "11 Reprenderé también por vosotros al devorador, y no os destruirá el fruto de la tierra, ni vuestra vid en el campo será estéril, dice Jehová de los ejércitos. 12 Y todas las naciones os dirán bienaventurados; porque seréis tierra deseable, dice Jehová de los ejércitos." },
        { ref: "Mateo 25:1-5", texto: "1 Entonces el reino de los cielos será semejante a diez vírgenes que tomando sus lámparas, salieron a recibir al esposo. 2 Cinco de ellas eran prudentes y cinco insensatas. 3 Las insensatas, tomando sus lámparas, no tomaron consigo aceite; 4 mas las prudentes tomaron aceite en sus vasijas, juntamente con sus lámparas. 5 Y tardándose el esposo, cabecearon todas y se durmieron." },
        { ref: "Mateo 5:14-16", texto: "14 Vosotros sois la luz del mundo; una ciudad asentada sobre un monte no se puede esconder. 15 Ni se enciende una luz y se pone debajo de un almud, sino sobre el candelero, y alumbra a todos los que están en casa. 16 Así alumbre vuestra luz delante de los hombres, para que vean vuestras buenas obras, y glorifiquen a vuestro Padre que está en los cielos." },
        { ref: "Malaquías 4:1-6", texto: "1 Porque he aquí, viene el día ardiente como un horno, y todos los soberbios y todos los que hacen maldad serán estopa; aquel día que vendrá los abrasará, ha dicho Jehová de los ejércitos, y no les dejará ni raíz ni rama. 2 Mas a vosotros los que teméis mi nombre, nacerá el Sol de justicia, y en sus alas traerá salvación; y saldréis, y saltaréis como becerros de la manada. 3 Hollaréis a los malos, los cuales serán ceniza bajo las plantas de vuestros pies, en el día en que yo actúe, ha dicho Jehová de los ejércitos. 4 Acordaos de la ley de Moisés mi siervo, al cual encargué en Horeb ordenanzas y leyes para todo Israel. 5 He aquí, yo os envío el profeta Elías, antes que venga el día de Jehová, grande y terrible. 6 El hará volver el corazón de los padres hacia los hijos, y el corazón de los hijos hacia los padres, no sea que yo venga y hiera la tierra con maldición." }
    ];

    // Obtener el día actual del mes (1-31)
    const fecha = new Date();
    const dia = fecha.getDate();
    const indice = (dia - 1) % citasBiblicas.length;
    const citaDelDia = citasBiblicas[indice];

    if (elementoTitulo) {
        elementoTitulo.textContent = citaDelDia.ref;
    }
    
    if (elementoTexto) {
        // Reemplazamos los números de los versículos para poder darles estilo y usamos innerHTML.
        const textoConEstilo = citaDelDia.texto.replace(/(\d+)/g, '<span class="numero-versiculo-rojo">$1</span>');
        elementoTexto.innerHTML = textoConEstilo;
    }
});